In [1]:
import numpy as np

In [2]:
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

a_np = np.array(a)
a_np

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
a_np.size

12

In [4]:
a_np[0][0:2]

array([1, 2])

In [5]:
B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

X = np.dot(a_np,B)
X

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])